# ===============================
#   STARSHIP PROMPT CONFIG
# ===============================

[[battery.display]]
threshold = 60
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[character]
success_symbol = "➜"
error_symbol = "✗"
vicmd_symbol = "❮"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[directory]
truncation_length = 6
truncate_to_repo = true
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
trim_at = "."
disabled = false

[line_break]
disabled = false

[python]
symbol = "🐍 "
pyenv_version_name = false
pyenv_prefix = "pyenv"
style = "bold yellow"
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

# ===============================
#   GIT MODULES (improved)
# ===============================

[git_branch]
symbol = "🌱 "
format = "on [$symbol$branch]($style) "
style = "bold green"

[git_commit]
commit_hash_length = 7
tag_symbol = "🏷 "

[git_status]
# Deutlichere Icons für den Git-Status
format = "([$all_status$ahead_behind]($style) )"
style = "bold cyan"
stashed = "📦 "
modified = "📝 "
staged = "✔ "
deleted = "🗑 "
untracked = "✨ "
renamed = "🔀 "
ahead = "⬆${count}"
behind = "⬇${count}"
diverged = "↕${ahead_count}/${behind_count}"
conflicted = "⚔ "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
rebase = "🔄 rebase"
merge = "🔀 merge"
am = "📬 am"
cherry_pick = "🍒 pick"
bisect = "🔍 bisect"
revert = "↩ revert"
style = "bold purple"

